// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMh2yhvoDZii0T8jP2uiQmROwQfxQXat8',
    appId: '1:608688891109:web:7540640a24c4e663c0600c',
    messagingSenderId: '608688891109',
    projectId: 'gestion-tickets-9e08f',
    authDomain: 'gestion-tickets-9e08f.firebaseapp.com',
    storageBucket: 'gestion-tickets-9e08f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdQavDxdBDlUbqNOS7kHCJX9Kq0XaB9h0',
    appId: '1:608688891109:android:045e6f69268ea5f0c0600c',
    messagingSenderId: '608688891109',
    projectId: 'gestion-tickets-9e08f',
    storageBucket: 'gestion-tickets-9e08f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuFSxzNyPGFmL-eNKADajPGEUBnL427cE',
    appId: '1:608688891109:ios:769c222bceb8444bc0600c',
    messagingSenderId: '608688891109',
    projectId: 'gestion-tickets-9e08f',
    storageBucket: 'gestion-tickets-9e08f.appspot.com',
    iosBundleId: 'com.example.gestionTickets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuFSxzNyPGFmL-eNKADajPGEUBnL427cE',
    appId: '1:608688891109:ios:b42e46f5d75c77afc0600c',
    messagingSenderId: '608688891109',
    projectId: 'gestion-tickets-9e08f',
    storageBucket: 'gestion-tickets-9e08f.appspot.com',
    iosBundleId: 'com.example.gestionTickets.RunnerTests',
  );
}
